apiVersion: v1
kind: Service
metadata:
  name: emyu-backend-service
spec:
  selector:
    app: emyu-backend
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  type: ClusterIP
