apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emyu-shop-backend
  template:
    metadata:
      labels:
        app: emyu-shop-backend
    spec:
      containers:
      - name: backend
        image: muhammadaryasuherman/emyu-shop-backend:master
        ports:
        - containerPort: 9000
        livenessProbe:
          httpGet:
            path: /health
            port: 9000
          initialDelaySeconds: 5
          periodSeconds: 10
