apiVersion: apps/v1
kind: Deployment
metadata:
  name: emyu-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emyu-backend
  template:
    metadata:
      labels:
        app: emyu-backend
    spec:
      containers:
      - name: emyu-backend
        image: muhammadaryasuherman/emyu-shop-backend:cache
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: emyu-backend
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  type: NodePort
