apiVersion: apps/v1
kind: Deployment
metadata:
  name: emyu-backend
  labels:
    app: emyu-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emyu-backend
  template:
    metadata:
      labels:
        app: emyu-backend
    spec:
      containers:
      - name: emyu-backend
        image: muhammadaryasuherman/emyu-shop-backend:master
        ports:
        - containerPort: 9000
        env:
        - name: NODE_ENV
          value: "production"
