FROM node:16

WORKDIR /app 

COPY package*.json ./
RUN npm install

# Copy seluruh proyek, termasuk folder `data`
COPY . .

EXPOSE 9000
CMD ["json-server", "--watch", "/data/product.json", "--port", "9000"]
