# Gunakan Node.js sebagai base image
FROM node:20

# Tentukan direktori kerja di dalam container
WORKDIR /app

# Salin file package.json dan package-lock.json
COPY package*.json ./

# Instal dependensi aplikasi
RUN npm install

# Salin semua file proyek ke dalam container
COPY . .

# Bangun aplikasi frontend
RUN npm run build

# Ekspos port yang akan digunakan aplikasi
EXPOSE 3000

# Jalankan server menggunakan package seperti serve
RUN npm install -g serve
CMD ["serve", "-s", "build", "-l", "3000"]
