version: '3'

services:
  backend:
    container_name: emyu-shop-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
    networks:
      - emyu-shop-network

  frontend:
    container_name: emyu-shop-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://emyu-shop-backend:9000 # URL untuk mengakses backend dari frontend
    depends_on:
      - backend
    networks:
      - emyu-shop-network

networks:
  emyu-shop-network:
    driver: bridge
