apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emyu-shop-frontend
  template:
    metadata:
      labels:
        app: emyu-shop-frontend
    spec:
      containers:
      - name: frontend
        image: muhammadaryasuherman/emyu-shop-frontend:master
        ports:
        - containerPort: 5173
