apiVersion: apps/v1
kind: Deployment
metadata:
  name: emyu-frontend
  labels:
    app: emyu-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emyu-frontend
  template:
    metadata:
      labels:
        app: emyu-frontend
    spec:
      containers:
      - name: emyu-frontend
        image: muhammadaryasuherman/emyu-shop-frontend:master
        ports:
        - containerPort: 5173
        env:
        - name: NODE_ENV
          value: "production"
