global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'emyu-shop-backend'
    static_configs:
      - targets: ['backend-service:9000']
  - job_name: 'emyu-shop-frontend'
    static_configs:
      - targets: ['frontend-service:80']
