apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 9000        # Port internal Service
      targetPort: 9000  # Port di container backend
      nodePort: 31000   # Port tetap untuk akses dari luar (opsional, bisa dihilangkan agar otomatis)
  type: NodePort
