# frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: muhammadaryasuherman/emyu-shop-frontend:master
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL  # Ubah ke VITE_API_URL
          value: "http://backend-service:9000"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 45
          periodSeconds: 20
        startupProbe:
          httpGet:
            path: /
            port: 5173
          failureThreshold: 30
          periodSeconds: 10