# frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    service.kubernetes.io/load-balancer-type: "NodePort"
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 5173
  type: LoadBalancer