apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: tes  # Tambahkan namespace
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  type: NodePort
