name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Images
      run: |
        TAG=${GITHUB_SHA::7}
        docker build -t muhammadaryasuherman/emyu-shop-backend:latest -t muhammadaryasuherman/emyu-shop-backend:$TAG -f dockerfile-backend .
        docker build -t muhammadaryasuherman/emyu-shop-frontend:latest -t muhammadaryasuherman/emyu-shop-frontend:$TAG -f dockerfile-frontend .

    - name: List Docker Images
      run: docker images  # Menampilkan daftar image yang telah dibuat untuk verifikasi

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Tests
      run: |
        npm install
        npm test

  push:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Images
      run: |
        TAG=${GITHUB_SHA::7}
        docker push muhammadaryasuherman/emyu-shop-backend:latest
        docker push muhammadaryasuherman/emyu-shop-frontend:latest
        docker push muhammadaryasuherman/emyu-shop-backend:$TAG
        docker push muhammadaryasuherman/emyu-shop-frontend:$TAG
