name: CI/CD for Emyu-Shop

on:
  push:
    branches:
      - master
      - Tes
    paths:
      - 'dockerfile-backend'
      - 'dockerfile-frontend'
      - 'src/**'
      - 'data/**'
      - '.github/workflows/**'
      - 'k8s/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend Docker Image
      run: |
        docker build -t muhammadaryasuherman/emyu-shop-backend:cache -f dockerfile-backend .
        docker push muhammadaryasuherman/emyu-shop-backend:cache

    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t muhammadaryasuherman/emyu-shop-frontend:cache -f dockerfile-frontend .
        docker push muhammadaryasuherman/emyu-shop-frontend:cache

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Backend Image
      run: docker pull muhammadaryasuherman/emyu-shop-backend:cache

    - name: Pull Frontend Image
      run: docker pull muhammadaryasuherman/emyu-shop-frontend:cache

    - name: Test Backend
      run: docker run --rm muhammadaryasuherman/emyu-shop-backend:cache npm test

    - name: Test Frontend
      run: docker run --rm muhammadaryasuherman/emyu-shop-frontend:cache npm test

  push:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Backend Image
      run: docker pull muhammadaryasuherman/emyu-shop-backend:cache

    - name: Pull Frontend Image
      run: docker pull muhammadaryasuherman/emyu-shop-frontend:cache

    - name: Retag and Push Backend Image
      run: |
        if [ "${{ github.ref_name }}" == "Tes" ]; then
          docker tag muhammadaryasuherman/emyu-shop-backend:cache muhammadaryasuherman/emyu-shop-backend:tes
          docker push muhammadaryasuherman/emyu-shop-backend:tes
        else
          docker tag muhammadaryasuherman/emyu-shop-backend:cache muhammadaryasuherman/emyu-shop-backend:master
          docker push muhammadaryasuherman/emyu-shop-backend:master
        fi

    - name: Retag and Push Frontend Image
      run: |
        if [ "${{ github.ref_name }}" == "Tes" ]; then
          docker tag muhammadaryasuherman/emyu-shop-frontend:cache muhammadaryasuherman/emyu-shop-frontend:tes
          docker push muhammadaryasuherman/emyu-shop-frontend:tes
        else
          docker tag muhammadaryasuherman/emyu-shop-frontend:cache muhammadaryasuherman/emyu-shop-frontend:master
          docker push muhammadaryasuherman/emyu-shop-frontend:master
        fi

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: push

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Minikube
      uses: medyagh/setup-minikube@master
      
    - name: Deploy to Kubernetes
      run: |
        eval $(minikube docker-env)
        if [ "${{ github.ref_name }}" == "Tes" ]; then
          kubectl apply -f k8s/ -n tes
        else
          kubectl apply -f k8s/
        fi
        kubectl get pods
        kubectl get services
