name: CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION_TAG: "${{ github.sha }}"  # Mendefinisikan VERSION_TAG untuk digunakan di semua langkah
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Images
        run: |
          echo "Building backend image with tags: master and $VERSION_TAG"
          docker build -t muhammadaryasuherman/emyu-shop-backend:master -t muhammadaryasuherman/emyu-shop-backend:$VERSION_TAG -f dockerfile-backend .
          
          echo "Building frontend image with tags: master and $VERSION_TAG"
          docker build -t muhammadaryasuherman/emyu-shop-frontend:master -t muhammadaryasuherman/emyu-shop-frontend:$VERSION_TAG -f dockerfile-frontend .

      - name: List Docker Images After Build
        run: docker images  # Verifikasi bahwa image telah dibuat

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          npm install
          npm test

  push:
    runs-on: ubuntu-latest
    needs: [build, test]
    env:
      VERSION_TAG: "${{ github.sha }}"  # Mendefinisikan VERSION_TAG untuk digunakan di semua langkah
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Docker Image
        run: |
          docker push muhammadaryasuherman/emyu-shop-backend:master
          docker push muhammadaryasuherman/emyu-shop-backend:$VERSION_TAG

      - name: Push Frontend Docker Image
        run: |
          docker push muhammadaryasuherman/emyu-shop-frontend:master
          docker push muhammadaryasuherman/emyu-shop-frontend:$VERSION_TAG
