name: CI/CD for Emyu-Shop

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Images
        run: |
          VERSION_TAG=$(date +'%Y%m%d')-${{ github.sha }}
          docker build -t muhammadaryasuherman/emyu-shop-backend:master -t muhammadaryasuherman/emyu-shop-backend:$VERSION_TAG -f Dockerfile.backend .
          docker build -t muhammadaryasuherman/emyu-shop-frontend:master -t muhammadaryasuherman/emyu-shop-frontend:$VERSION_TAG -f Dockerfile.frontend .
        env:
          VERSION_TAG: ${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run Backend Tests
        run: |
          # Jalankan perintah testing untuk backend
          echo "Backend tests running..."

      - name: Run Frontend Tests
        run: |
          # Jalankan perintah testing untuk frontend
          echo "Frontend tests running..."

  push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Docker Image
        run: |
          docker push muhammadaryasuherman/emyu-shop-backend:master
          docker push muhammadaryasuherman/emyu-shop-backend:$VERSION_TAG

      - name: Push Frontend Docker Image
        run: |
          docker push muhammadaryasuherman/emyu-shop-frontend:master
          docker push muhammadaryasuherman/emyu-shop-frontend:$VERSION_TAG
        env:
          VERSION_TAG: ${{ github.sha }}
