name: CI/CD for Emyu-Shop

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Build Backend
    - name: Build Backend Docker Image
      run: docker build -t emyu-shop-backend:latest -f dockerfile-backend .

    # Build Frontend
    - name: Build Frontend Docker Image
      run: docker build -t emyu-shop-frontend:latest -f dockerfile-frontend .

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Test Backend
      run: |
        docker run --rm emyu-shop-backend:latest npm test
        # Sesuaikan perintah ini dengan command test backend

    - name: Test Frontend
      run: |
        docker run --rm emyu-shop-frontend:latest npm test
        # Sesuaikan perintah ini dengan command test frontend

  push:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Push Backend Image
    - name: Push Backend Image to Docker Hub
      run: |
        docker tag emyu-shop-backend:latest muhammadaryasuherman/emyu-shop-backend:latest
        docker push muhammadaryasuherman/emyu-shop-backend:latest

    # Push Frontend Image
    - name: Push Frontend Image to Docker Hub
      run: |
        docker tag emyu-shop-frontend:latest muhammadaryasuherman/emyu-shop-frontend:latest
        docker push muhammadaryasuherman/emyu-shop-frontend:latest
