name: CI/CD for Emyu-Shop with Kubernetes

on:
  push:
    branches:
      - master
      - Tes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Images
      run: |
        docker build -t muhammadaryasuherman/emyu-shop-backend:latest -f dockerfile-backend .
        docker build -t muhammadaryasuherman/emyu-shop-frontend:latest -f dockerfile-frontend .
        docker push muhammadaryasuherman/emyu-shop-backend:latest
        docker push muhammadaryasuherman/emyu-shop-frontend:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v1
      
    - name: Configure kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/frontend-service.yaml
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/backend-service.yaml
        kubectl apply -f k8s/hpa.yaml